export const products = [
  {
    name: "FULLPACKAGE",
    components: [
      // MOBILE ROBOT
      { name: "Arduino Nano with Cable", baseQty: 1 },
      { name: "TB6612 Motor driver", baseQty: 1 },
      { name: "3D Robot Frame", baseQty: 1 },
      { name: "TT20 DC MOTOR", baseQty: 2 },
      { name: "Jumpire Wires female to female", baseQty: 20 },
      { name: "Wheels", baseQty: 2 },
      { name: "Caster wheel", baseQty: 1 },
      { name: "Screw driver", baseQty: 1 },
      { name: "Screws and Knots", baseQty: 10 },
      { name: "Battery", baseQty: 2 },
      { name: "Battery Holder", baseQty: 1 },
      { name: "Spare accessories", baseQty: 1 },
      // BASIC KIT
      { name: "LED's", baseQty: 10 },
      { name: "Potentiometer", baseQty: 1 },
      { name: "LDR", baseQty: 2 },
      { name: "Resistor 220", baseQty: 10 },
      { name: "Resistor 1k", baseQty: 10 },
      { name: "Resistor 10k", baseQty: 10 },
      { name: "Buzzer", baseQty: 1 },
      { name: "Tact switch", baseQty: 5 },
      { name: "Male to Male", baseQty: 10 },
      { name: "JUMPER WIRES Female to male", baseQty: 10 },
      { name: "Half size breadboard", baseQty: 1 },
      // MICROCONTROLLER, SENSOR AND ACTUATORS
      { name: "Arduino Uno with Cable", baseQty: 1 },
      { name: "Humidity sensor", baseQty: 1 },
      { name: "Sound sensor", baseQty: 1 },
      { name: "Ultrasonic sensor", baseQty: 1 },
      { name: "SG90 servo motor", baseQty: 1 },
      { name: "5 Channel IR Sensor", baseQty: 1 },
      { name: "1 Channel Relay", baseQty: 1 },
      { name: "HC-05 Bluetooth module", baseQty: 1 },
      { name: "ESP8266 Node MCU Wifi Module with micro cable", baseQty: 1 },
      { name: "Soil moisture", baseQty: 1 },
      { name: "LCD with I2C", baseQty: 1 },
    ],
  },
  {
    name: "EROBOT v1.5",
    components: [
      {
        name: "Arduino Nano with Cable and PCB made by erovoutika",
        baseQty: 1,
      },
      { name: "Ultrasonic sensor", baseQty: 1 },
      { name: "SG90 servo motor", baseQty: 1 },
      { name: "5 Channel IR Sensor", baseQty: 1 },
      { name: "Jumpire Wires female to female", baseQty: 20 },
      { name: "Screw driver", baseQty: 1 },
      { name: "Screws and Knots", baseQty: 10 },
      { name: "Battery", baseQty: 2 },
      { name: "Battery Holder", baseQty: 1 },
      { name: "TB6612 Motor driver", baseQty: 1 },
      { name: "LCD 12C", baseQty: 1 },
      { name: "3D Robot Frame", baseQty: 1 },
      { name: "RC Gear Motor", baseQty: 2 },
      { name: "Wheels", baseQty: 2 },
      { name: "Caster wheel", baseQty: 1 },
    ],
  },
  {
    name: "AI EROBOT",
    components: [],
  },
  {
    name: "EROBOT v2",
    components: [
      {
        name: "Arduino Nano with Cable and PCB made by erovoutika",
        baseQty: 1,
      },
      { name: "8 Channel IR Sensor", baseQty: 1 },
      { name: "Male to Male Connecting wires", baseQty: 10 },
      { name: "Female to male Connecting wires", baseQty: 10 },
      { name: "Screw driver", baseQty: 1 },
      { name: "Screws and Knots", baseQty: 10 },
      { name: "Battery", baseQty: 2 },
      { name: "Battery Holder", baseQty: 1 },
      { name: "TB6612 Motor driver", baseQty: 1 },
      { name: "3D Robot Frame", baseQty: 1 },
      { name: "RC Gear Motor", baseQty: 2 },
      { name: "Wheels", baseQty: 2 },
      { name: "Caster wheel", baseQty: 1 },
      { name: "Wire cutter", baseQty: 1 },
      { name: "BOX", baseQty: 1 },
    ],
  },
  {
    name: "EROBOT v3",
    components: [
      { name: "X Motion MICROCONTROLLER", baseQty: 1 },
      {
        name: "8 Channel IR Sensor or 16 channel Jsumo IR sensor",
        baseQty: 1,
      },
      { name: "Male to Male Connecting wires", baseQty: 10 },
      { name: "Female to male Connecting wires", baseQty: 10 },
      { name: "Screw driver", baseQty: 1 },
      { name: "Screws and Knots", baseQty: 10 },
      { name: "Lipo Battery", baseQty: 1 },
      { name: "3D Robot Frame", baseQty: 1 },
      { name: "Jsumo Motor", baseQty: 2 },
      { name: "Wheels Silicon", baseQty: 2 },
      { name: "Caster Wheel", baseQty: 1 },
      { name: "Wire cutter", baseQty: 1 },
      { name: "BOX", baseQty: 1 },
    ],
  },
  {
    name: "ERO KIT 2024-02",
    components: [
      { name: "RASPBERRY PI4 BLACK CASE WITH FAN MOUNT", baseQty: 1 },
      { name: "RASPBERRY PI 4 MODEL B 4GB", baseQty: 1 },
      { name: "32GB SANDISK ULTRA MICROSD CARD CLASS 10", baseQty: 1 },
      { name: "RASPBERRY PI 4 HEATSINK ALUMINUM", baseQty: 1 },
      { name: "RASPBERRY PI FAN", baseQty: 1 },
      {
        name: "OKDO RASPBERRY PI 4 POWERSUPPLY PSU USB TYPE C WITH US PLUG 1.5M 5V 3A",
        baseQty: 1,
      },
    ],
  },
  {
    name: "Electronics kit v1",
    components: [
      // SOLDERING KIT
      { name: "Soldering Iron", baseQty: 1 },
      { name: "Soldering iron tip", baseQty: 5 },
      { name: "Desoldering pump", baseQty: 1 },
      { name: "Tin wire tube", baseQty: 1 },
      { name: "Soldering iron holder", baseQty: 1 },
      { name: "Sponge", baseQty: 1 },
      { name: "Tweezer", baseQty: 1 },
      { name: "Wire stripper cutter", baseQty: 1 },
      { name: "Electronic wire", baseQty: 2 },
      { name: "Cloth tool storage bag", baseQty: 1 },
      // BASIC KIT
      { name: "LED's", baseQty: 10 },
      { name: "Potentiometer", baseQty: 1 },
      { name: "LDR", baseQty: 2 },
      { name: "Resistor 220", baseQty: 10 },
      { name: "Resistor 1k", baseQty: 10 },
      { name: "Resistor 10k", baseQty: 10 },
      { name: "Buzzer", baseQty: 1 },
      { name: "Tact switch", baseQty: 5 },
      { name: "JUMPER WIRES Male to Male", baseQty: 10 },
      { name: "JUMPER WIRES Female to male", baseQty: 10 },
      { name: "HALF SIZE BREADBOARD", baseQty: 1 },
      { name: "UNIVERSAL PCB BREADBOARD", baseQty: 1 },
    ],
  },
  {
    name: "ERO KIT 2024-01",
    components: [
      // SOLDERING KIT
      { name: "Soldering Iron", baseQty: 1 },
      { name: "Soldering iron tip", baseQty: 5 },
      { name: "Desoldering pump", baseQty: 1 },
      { name: "Tin wire tube", baseQty: 1 },
      { name: "Soldering iron holder", baseQty: 1 },
      { name: "Sponge", baseQty: 1 },
      { name: "Tweezer", baseQty: 1 },
      { name: "Wire stripper cutter", baseQty: 1 },
      { name: "Electronic wire", baseQty: 2 },
      { name: "Cloth tool storage bag", baseQty: 1 },
      // BASIC KIT
      { name: "LED's", baseQty: 10 },
      { name: "Potentiometer", baseQty: 1 },
      { name: "LDR", baseQty: 2 },
      { name: "Resistor 220", baseQty: 10 },
      { name: "Resistor 1k", baseQty: 10 },
      { name: "Resistor 10k", baseQty: 10 },
      { name: "Buzzer", baseQty: 1 },
      { name: "Tact switch", baseQty: 5 },
      { name: "JUMPER WIRES Male to Male", baseQty: 10 },
      { name: "JUMPER WIRES Female to male", baseQty: 10 },
      { name: "HALF SIZE BREADBOARD", baseQty: 1 },
      { name: "UNIVERSAL PCB BREADBOARD", baseQty: 1 },
      // MICROCONTROLLER, SENSOR AND ACTUATORS
      { name: "Arduino Uno with Cable", baseQty: 1 },
      { name: "Humidity sensor", baseQty: 1 },
      { name: "Sound sensor", baseQty: 1 },
      { name: "Ultrasonic sensor", baseQty: 1 },
      { name: "SG90 servo motor", baseQty: 1 },
      { name: "5 Channel IR Sensor", baseQty: 1 },
      { name: "1 Channel Relay", baseQty: 1 },
      { name: "HC-05 Bluetooth module", baseQty: 1 },
      { name: "ESP8266 Node MCU Wifi Module with micro cable", baseQty: 1 },
      { name: "Soil moisture", baseQty: 1 },
      { name: "LCD with I2C", baseQty: 1 },
    ],
  },
];
